#server start
server:
  port: 8082
#server end

#ldap start
ldap:
  contextSource:
    url: ldap://localhost:389
    base: dc=maxcrc,dc=com
    userDn: cn=Manager,dc=maxcrc,dc=com
    password: secret
    referral: follow
#ldap end

#thymeleaf start
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
#开发时关闭缓存,不然没法看到实时页面
    cache: false
#thymeleaf end

log:
  path: E:/logs
  name: authentication

